import { ShieldCheck, Zap, Smartphone, CheckCircle2, Lock, Image as ImageIcon, LucideIcon } from "lucide-react"

export interface Feature {
    slug: string
    icon: LucideIcon
    title: string
    description: string
    longDescription: string
    benefits: string[]
}

export const FEATURES: Feature[] = [
    {
        slug: "lightning-fast-processing",
        icon: Zap,
        title: "Lightning Fast",
        description: "Process images in under 3 seconds using our optimized edge infrastructure.",
        longDescription: "Our AI engine is distributed across global edge nodes, ensuring that your image is processed by the server closest to you. This architecture allows for sub-3-second watermark removal, making it one of the fastest tools on the market. Whether you have one image or a hundred, our parallel processing pipeline handles the load instantly.",
        benefits: [
            "Sub-3-second processing time",
            "Global edge network",
            "Parallel processing for batch uploads",
            "Instant preview generation"
        ]
    },
    {
        slug: "private-secure",
        icon: Lock,
        title: "100% Private",
        description: "Your images are processed in memory and immediately discarded. No storage, no snooping.",
        longDescription: "Privacy is our top priority. We employ a stateless processing architecture where your images are uploaded to ephemeral RAM storage, processed instantly, and wiped from memory required. We never write your user content to disk, and no human ever sees your uploads.",
        benefits: [
            "RAM-only processing",
            "No disk storage",
            "Auto-deletion after processing",
            "TLS encryption in transit"
        ]
    },
    {
        slug: "quality-preserved",
        icon: ImageIcon,
        title: "Quality Preserved",
        description: "We only remove the watermark. Your image resolution and details remain untouched.",
        longDescription: "Unlike other tools that compress or resize your images, our AI model works on the pixel level to surgically remove only the watermark artifacts. The rest of your image remains bit-perfect, preserving the original resolution, file format, and color profiles.",
        benefits: [
            "No compression artifacts",
            "Original resolution maintained",
            "Support for 4K+ images",
            "ICC profile preservation"
        ]
    },
    {
        slug: "gemini-optimized",
        icon: ShieldCheck,
        title: "Gemini Optimized",
        description: "Specifically tuned for Google's visible branding and logo artifacts used in Gemini images.",
        longDescription: "Our AI models are trained on a massive dataset of Google Gemini and Imagen 3 generated images. This specialization allows us to accurately detect and remove specific watermark patterns, semi-transparent logos, and 'generated by AI' badges with higher precision than generic object removers.",
        benefits: [
            "Tuned for Google Gemini logos",
            "Handles semi-transparent overlays",
            "Removes corner badges",
            "Updated for Imagen 3"
        ]
    },
    {
        slug: "no-signup",
        icon: CheckCircle2,
        title: "No Signup Required",
        description: "Start removing watermarks instantly. No email, no account, no friction.",
        longDescription: "We believe in friction-less tools. You shouldn't have to navigate a complex dashboard or hand over your email just to process an image. Our free tier is open to everyone, instantly. Just drag, drop, and download.",
        benefits: [
            "Instant access",
            "No email spam",
            "No credit card required for free tier",
            "Anonymous usage"
        ]
    },
    {
        slug: "mobile-ready",
        icon: Smartphone,
        title: "Works on Mobile",
        description: "Fully responsive design allowing you to clean images directly from your phone.",
        longDescription: "GeminiWatermark.ai is built with a mobile-first approach. Our responsive interface works perfectly on iOS and Android browsers, allowing you to clean up saved images or screenshots directly from your camera roll without needing a computer.",
        benefits: [
            "Responsive touch interface",
            "Works on iOS and Android",
            "Fast loading on mobile networks",
            "Touch-friendly controls"
        ]
    }
]
